#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 29 13:18:09 2019

@author: sc2195
"""
from os import listdir
from os.path import isfile, join
import numpy as np
import xlsxwriter
import time

methods = ['MNDO', 'AM1', 'PM3', 'PM6', 'MNDOD', 'PM7']

def tabulate(file):
     onlyfiles = [f for f in listdir(file) if isfile(join(file, f))]
     surfaces = [i for i in onlyfiles if '.esp' in i]

     workbook = xlsxwriter.Workbook('results_{:}.xlsx'.format(file))
     worksheet = workbook.add_worksheet()

     for i in range(len(surfaces)):
          with open(file+'/'+surfaces[i]) as esp:

               #take InChiKey from file name
               name = surfaces[i].split('_')[0]

               #read data from file
               lineList = esp.readlines()
               data = [np.asarray([float(k) for k in j.strip().split('  ')]) for j in lineList[1:]]
               data = np.transpose(np.asarray(data))
	  
               potentials = data[0]
	
               max_ptl = max(potentials)
               min_ptl = min(potentials)
	
               #write relevant data to workbook
               index = str(i+1)
               worksheet.write('A'+index, name)
               worksheet.write('B'+index, max_ptl)
               worksheet.write('C'+index, min_ptl)

     workbook.close()
     return

for n in range(len(methods)):
     tabulate(methods[n])
     print('\n{:} results generated: {:}\n'.format(methods[n], time.ctime()))
     print('Saved to file: results_{:}.xlsx\n\n'.format(methods[n]))
