#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 29 13:18:09 2019

@author: sc2195
"""
from os import listdir
from os.path import isfile, join
import csv
import time

methods = ['MNDO', 'AM1', 'PM3', 'PM6', 'MNDOD', 'PM7']

def tabulate(method):
     #create a list of all MOPAC output files in the directory
     onlyfiles = [f for f in listdir('nicola_mops') if isfile(join('nicola_mops', f))]
     files = [i for i in onlyfiles if '{:}.mgf.jvxl'.format(method) in i]
     
     rows = []
     
     #iterate through output files
     for file in files:
          with open('nicola_mops/'+file) as jvxl:
              name = file.split('_')[1]
              lineList = jvxl.readlines()
              data = [i.split(' ') for i in lineList]
              
              potmin = float(data[0][3])
              potmax = float(data[0][4].strip())
              
              rows.append([name, potmax, potmin])
              
     with open('results_{:}.csv'.format(method), 'w') as results:
         writer = csv.writer(results)
         writer.writerows(rows)

     results.close()
     return

for n in range(len(methods)):
     tabulate(methods[n])
     print('\n{:} results generated: {:}\n'.format(methods[n], time.ctime()))
     print('Saved to file: results_{:}.csv\n\n'.format(methods[n]))
